name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/pngwing-1.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1.png
    - assets/page-1/images/pngwing-1-7Tm.png
    - assets/page-1/images/pngwing-1-D9H.png
    - assets/page-1/images/free-home-icon-2502-thumb-1.png
    - assets/page-1/images/pngwing-1-jKu.png
    - assets/page-1/images/pizza-de-calabresa-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-vmV.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1-82K.png
    - assets/page-1/images/pizza-de-calabresa-1-BWP.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-Pfd.png
    - assets/page-1/images/pngwing-1-yJP.png
    - assets/page-1/images/polenta-frita-1.png
    - assets/page-1/images/icone-pessoa-2.png
    - assets/page-1/images/pasteis-1.png
    - assets/page-1/images/pngwing-1-GoZ.png
    - assets/page-1/images/pizza-de-calabresa-1-sxK.png
    - assets/page-1/images/icone-pessoa-2-c2b.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-9v7.png
    - assets/page-1/images/bebidas-1.png
    - assets/page-1/images/polenta-frita-1-wH9.png
    - assets/page-1/images/icone-pessoa-2-dS7.png
    - assets/page-1/images/icone-pessoa-2-NPh.png
    - assets/page-1/images/pizza-de-calabresa-1-K43.png
    - assets/page-1/images/rectangle-9-AzK.png
    - assets/page-1/images/pngwing-1-wbd.png
    - assets/page-1/images/pngwing-1-ZN7.png
    - assets/page-1/images/icone-pessoa-2-7Pd.png
    - assets/page-1/images/pngwing-1-rs1.png
    - assets/page-1/images/pngwing-1-2Wb.png
    - assets/page-1/images/polenta-frita-1-zCX.png
    - assets/page-1/images/polenta-frita-1-1a7.png
    - assets/page-1/images/rectangle-9-fCj.png
    - assets/page-1/images/rectangle-9-SCo.png
    - assets/page-1/images/pngwing-1-P83.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-3iP.png
    - assets/page-1/images/polenta-frita-1-bHy.png
    - assets/page-1/images/pizza-de-calabresa-1-g8w.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-zvK.png
    - assets/page-1/images/pizza-de-calabresa-1-Gum.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-1MZ.png
    - assets/page-1/images/rectangle-9-K8b.png
    - assets/page-1/images/pizza-de-calabresa-1-GJ3.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/polygon-1-yyh.png
    - assets/page-1/images/icone-pessoa-2-G4w.png
    - assets/page-1/images/icone-pessoa-2-DF5.png
    - assets/page-1/images/pngwing-1-7Ao.png
    - assets/page-1/images/polygon-1-jtj.png
    - assets/page-1/images/rectangle-9-65u.png
    - assets/page-1/images/icone-edicao-1.png
    - assets/page-1/images/rectangle-9-zBH.png
    - assets/page-1/images/polenta-frita-1-BfM.png
    - assets/page-1/images/polygon-1-VAF.png
    - assets/page-1/images/pizza-de-calabresa-1-dXM.png
    - assets/page-1/images/rectangle-9-TXd.png
    - assets/page-1/images/rectangle-9-n47.png
    - assets/page-1/images/pizza-de-calabresa-1-KJw.png
    - assets/page-1/images/rectangle-9-9WP.png
    - assets/page-1/images/rectangle-9-VaF.png
    - assets/page-1/images/pasteis-1-Las.png
    - assets/page-1/images/pngwing-1-u8B.png
    - assets/page-1/images/polygon-1-dt3.png
    - assets/page-1/images/laa-burger-cortada-1.png
    - assets/page-1/images/laa-burger-cortada-1-shH.png
    - assets/page-1/images/polygon-1-VM9.png
    - assets/page-1/images/rectangle-9-NWK.png
    - assets/page-1/images/polygon-1-X8K.png
    - assets/page-1/images/pngwing-1-Tnf.png
    - assets/page-1/images/pngwing-1-RzP.png
    - assets/page-1/images/pngwing-1-447.png
    - assets/page-1/images/polygon-1-ziT.png
    - assets/page-1/images/pngwing-1-kxX.png
    - assets/page-1/images/rectangle-9-XTV.png
    - assets/page-1/images/pngwing-1-VfD.png
    - assets/page-1/images/rectangle-9-GAB.png
    - assets/page-1/images/icone-pessoa-2-pxP.png
    - assets/page-1/images/pngwing-1-biF.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-kr3.png
    - assets/page-1/images/rectangle-9-X67.png
    - assets/page-1/images/pngwing-1-sfm.png
    - assets/page-1/images/pngwing-1-eRd.png
    - assets/page-1/images/pizza-de-calabresa-1-Qfh.png
    - assets/page-1/images/rectangle-9-NsR.png
    - assets/page-1/images/rectangle-9-wvX.png
    - assets/page-1/images/rectangle-9-KXm.png
    - assets/page-1/images/pngwing-1-tqm.png
    - assets/page-1/images/rectangle-9-Zbm.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1-wmy.png
    - assets/page-1/images/polygon-1-Gab.png
    - assets/page-1/images/rectangle-9-Mxj.png
    - assets/page-1/images/image-1.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1-fSo.png
    - assets/page-1/images/pizza-de-calabresa-1-9VZ.png
    - assets/page-1/images/pizza-de-calabresa-1-RE7.png
    - assets/page-1/images/polygon-1-Ayd.png
    - assets/page-1/images/imagem-prato.png
    - assets/page-1/images/imagen-comparar.png
    - assets/page-1/images/pizza-de-calabresa-1-KaX.png
    - assets/page-1/images/imagem-carrinho.png
    - assets/page-1/images/polenta-frita-1-CBh.png
    - assets/page-1/images/imagem-cardpio.png
    - assets/page-1/images/polenta-frita-1-Qej.png
    - assets/page-1/images/imagem-categorias.png
    - assets/page-1/images/pngwing-1-se7.png
    - assets/page-1/images/bebidas-1-5yH.png
    - assets/page-1/images/icone-pessoa-2-KvF.png
    - assets/page-1/images/pngwing-1-kpo.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-r3q.png
    - assets/page-1/images/pngwing-1-8Ss.png
    - assets/page-1/images/pizza-de-calabresa-1-W9D.png
    - assets/page-1/images/rectangle-9-6EB.png
    - assets/page-1/images/pngwing-1-jtb.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-Bd1.png
    - assets/page-1/images/rectangle-9-CbZ.png
    - assets/page-1/images/pizza-de-calabresa-1-8Sb.png
    - assets/page-1/images/polygon-1-dbV.png
    - assets/page-1/images/prottipofinal-1.png
    - assets/page-1/images/rectangle-9-KAw.png
    - assets/page-1/images/pngwing-1-Npo.png
    - assets/page-1/images/pizza-de-calabresa-1-NM5.png
    - assets/page-1/images/polygon-1-fXu.png
    - assets/page-1/images/arrow-9.png
    - assets/page-1/images/icone-pessoa-2-xA3.png
    - assets/page-1/images/pizza-de-calabresa-1-mRH.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-huq.png
    - assets/page-1/images/pngwing-1-o7M.png
    - assets/page-1/images/polygon-1-18s.png
    - assets/page-1/images/pngwing-1-FDZ.png
    - assets/page-1/images/pngwing-1-RM1.png
    - assets/page-1/images/icone-pessoa-2-JmD.png
    - assets/page-1/images/pngwing-1-pfZ.png
    - assets/page-1/images/icone-pessoa-2-wqy.png
    - assets/page-1/images/pngwing-1-dBV.png
    - assets/page-1/images/icone-pessoa-2-gCo.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-6dM.png
    - assets/page-1/images/icone-pessoa-2-84o.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-FXM.png
    - assets/page-1/images/arrow-9-Uym.png
    - assets/page-1/images/loading-icon-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-wHH.png
    - assets/page-1/images/pngwing-1-QVu.png
    - assets/page-1/images/check-icon-1.png
    - assets/page-1/images/icone-pessoa-2-qZq.png
    - assets/page-1/images/polygon-1-rEb.png
    - assets/page-1/images/arrow-2.png
    - assets/page-1/images/check-icon-2.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-isH.png
    - assets/page-1/images/pngwing-1-qgK.png
    - assets/page-1/images/polygon-1-QAj.png
    - assets/page-1/images/arrow-8.png
    - assets/page-1/images/check-icon-3.png
    - assets/page-1/images/polygon-1-nqm.png
    - assets/page-1/images/arrow-7.png
    - assets/page-1/images/arrow-4.png
    - assets/page-1/images/arrow-10.png
    - assets/page-1/images/line-10.png
    - assets/page-1/images/arrow-5.png
    - assets/page-1/images/arrow-6.png
    - assets/page-1/images/arrow-3.png
    - assets/page-1/images/arrow-11.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
