name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0 #^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/icone-pessoa-2.png
    - assets/page-1/images/icone-pessoa-2-Mn7.png
    - assets/page-1/images/icone-pessoa-2-WB9.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-oZR.png
    - assets/page-1/images/pasteis-1.png
    - assets/page-1/images/icone-edicao-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-m7V.png
    - assets/page-1/images/polygon-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-L5D.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1-o6X.png
    - assets/page-1/images/check-icon-1.png
    - assets/page-1/images/rectangle-9.png
    - assets/page-1/images/polenta-frita-1.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-DQj.png
    - assets/page-1/images/polygon-1-5xj.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1-QxP.png
    - assets/page-1/images/polygon-1-yhH.png
    - assets/page-1/images/loading-icon-1.png
    - assets/page-1/images/rectangle-9-8GX.png
    - assets/page-1/images/polygon-1-QyM.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-FW7.png
    - assets/page-1/images/laa-burger-cortada-1.png
    - assets/page-1/images/polygon-1-rV5.png
    - assets/page-1/images/polygon-1-bhZ.png
    - assets/page-1/images/rectangle-9-u7u.png
    - assets/page-1/images/rectangle-9-sy1.png
    - assets/page-1/images/pizza-de-calabresa-1.png
    - assets/page-1/images/icone-pessoa-2-b19.png
    - assets/page-1/images/rectangle-9-R8B.png
    - assets/page-1/images/icone-pessoa-2-5yR.png
    - assets/page-1/images/rectangle-9-79R.png
    - assets/page-1/images/icone-pessoa-2-fVh.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-AAs.png
    - assets/page-1/images/laa-burger-cortada-1-YHm.png
    - assets/page-1/images/icone-pessoa-2-ZwD.png
    - assets/page-1/images/pasteis-1-ayD.png
    - assets/page-1/images/polygon-1-Upw.png
    - assets/page-1/images/polenta-frita-1-jCT.png
    - assets/page-1/images/polenta-frita-1-gHM.png
    - assets/page-1/images/polygon-1-8ns.png
    - assets/page-1/images/polenta-frita-1-JvB.png
    - assets/page-1/images/check-icon-2.png
    - assets/page-1/images/arrow-9.png
    - assets/page-1/images/polenta-frita-1-EwR.png
    - assets/page-1/images/rectangle-9-5fm.png
    - assets/page-1/images/polygon-1-4Lf.png
    - assets/page-1/images/check-icon-3.png
    - assets/page-1/images/polygon-1-D7d.png
    - assets/page-1/images/rectangle-9-MVy.png
    - assets/page-1/images/rectangle-9-PTD.png
    - assets/page-1/images/arrow-9-GnT.png
    - assets/page-1/images/polygon-1-kwq.png
    - assets/page-1/images/icone-pessoa-2-8Py.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-wTd.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-rXy.png
    - assets/page-1/images/receitas-de-pizza-siciliana-2-730x449-1-1H1.png
    - assets/page-1/images/pizza-de-calabresa-1-mFV.png
    - assets/page-1/images/pizza-de-calabresa-1-6Kh.png
    - assets/page-1/images/icone-pessoa-2-BM9.png
    - assets/page-1/images/pizza-de-calabresa-1-eQP.png
    - assets/page-1/images/polygon-1-38B.png
    - assets/page-1/images/icone-pessoa-2-Bif.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-dU3.png
    - assets/page-1/images/polenta-frita-1-oUK.png
    - assets/page-1/images/rectangle-9-C5d.png
    - assets/page-1/images/pngwing-1.png
    - assets/page-1/images/pngwing-1-iX9.png
    - assets/page-1/images/pngwing-1-YCf.png
    - assets/page-1/images/pngwing-1-4QX.png
    - assets/page-1/images/pngwing-1-V1H.png
    - assets/page-1/images/pngwing-1-YVM.png
    - assets/page-1/images/pngwing-1-dFu.png
    - assets/page-1/images/pngwing-1-tf1.png
    - assets/page-1/images/pngwing-1-Vq9.png
    - assets/page-1/images/pngwing-1-Xao.png
    - assets/page-1/images/pizza-de-calabresa-1-PsD.png
    - assets/page-1/images/pngwing-1-hAP.png
    - assets/page-1/images/pngwing-1-3J7.png
    - assets/page-1/images/pngwing-1-ikw.png
    - assets/page-1/images/pngwing-1-Ymu.png
    - assets/page-1/images/pngwing-1-1xK.png
    - assets/page-1/images/pngwing-1-bDh.png
    - assets/page-1/images/pngwing-1-zBH.png
    - assets/page-1/images/polenta-frita-1-1Hy.png
    - assets/page-1/images/rectangle-9-vEs.png
    - assets/page-1/images/icone-pessoa-2-xpX.png
    - assets/page-1/images/free-home-icon-2502-thumb-1-aWT.png
    - assets/page-1/images/polenta-frita-1-6qV.png
    - assets/page-1/images/bebidas-1.png
    - assets/page-1/images/pngwing-1-h3D.png
    - assets/page-1/images/bebidas-1-cYP.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
